services:
  camera:
    image: hackrsackr/plant-cam:latest
    volumes:
      - /run/udev:/run/udev
      - ./:/app # remove this volume if you don't want to retrieve the captured images
      - "/etc/localtime:/etc/localtime:ro"
    build:
      context: app
      target: builder
    privileged: true
    ports:
      - "5000:5000"
    devices:
      - "/dev/vchiq:/dev/vchiq"
    restart: unless-stopped
    command: "python3 app.py"
