[project]
name = "plant-cam"
version = "0.1.0"
description = "timelapse camera and environmental info"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.0",
    "opencv-python>=4.10.0.84",
    "pandas>=2.2.3",
    "ruff>=0.8.4",
]
